<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <LangVersion>14.0</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>

        <UseWPF>true</UseWPF>
        <OutputType>WinExe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <!--<PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.3" />-->
        <!-- If you use the above, then you won't get the full package, but just the C# code, without some SQLite C library or something like that. -->

        <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.3" />
        <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3800.47" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    </ItemGroup>

</Project>
